---
title: "snippets"
format: gfm
---


Mutate multiple columns, keeping original and appending names to the new ones.

```{r message=FALSE}
library(dplyr)

data.frame(x1 = rnorm(5, mean = 100),
           x2 = rnorm(5, mean = 1000)) |> 
  mutate(across(everything(),
                .fns = list(log = ~log(.)),
                .names = '{fn}_{col}'))
```


Scraping Excel files embedded in a website. FHWA TVT example.

```{r message=FALSE}
library(rio)
library(rvest)

# main web page with links
URL <- 'https://www.fhwa.dot.gov/policyinformation/travel_monitoring/tvt.cfm'
pg <- read_html(URL)

# dataframe with links on webpage
root <- 'https://www.fhwa.dot.gov'
df <- data.frame(links = paste0(root, html_attr(html_nodes(pg, 'a'), 'href')))

# import Excel file
xlsx_url <- df$links[grep('.xlsx', df$links)][1]
xlsx_df <- import(xlsx_url, which = 6) # "which" selects the sheet name/number for Excel files
```



US map plotting

```{r}
library(usmap)

statepop |> 
  plot_usmap(data = _, region = 'state', values = 'pop_2015')

# dataframe can't have additional variables

# statepop |> 
  # dplyr::mutate(x = pop_2015 + 10) |> 
  # plot_usmap(data = _, region = 'state', values = 'pop_2015')

# Error in `[.data.frame`(result, , c(setdiff(names(result), names(data)), :
# undefined columns selected
```














